2013-11-27 01:33:38,372 [WARNING] django.request: Not Found: /contacts/
2013-11-27 01:34:04,529 [ERROR] django.request: Internal Server Error: /contact
Traceback (most recent call last):
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/middleware/common.py", line 79, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/contact/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2013-11-27 01:45:58,809 [ERROR] django.request: Internal Server Error: /contact/
Traceback (most recent call last):
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 227, in dispatch
    response = super(WizardView, self).dispatch(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 290, in post
    return self.render_done(form, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 332, in render_done
    done_response = self.done(final_form_list, **kwargs)
  File "/Users/mt/Documents/Programming/Python/django/projects/polltut/yt_tut/yt_tut/views.py", line 86, in done
    form_data = process_form_data(form_list)
  File "/Users/mt/Documents/Programming/Python/django/projects/polltut/yt_tut/yt_tut/views.py", line 102, in process_form_data
    ['gyrodecode@outlook.com'],fail_silently=False)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    connection=connection).send()
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/mail/message.py", line 255, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 88, in send_messages
    new_conn_created = self.open()
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 49, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 250, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 310, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 285, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
2013-11-27 01:53:03,343 [ERROR] django.request: Internal Server Error: /contact/
Traceback (most recent call last):
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 227, in dispatch
    response = super(WizardView, self).dispatch(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 290, in post
    return self.render_done(form, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 332, in render_done
    done_response = self.done(final_form_list, **kwargs)
  File "/Users/mt/Documents/Programming/Python/django/projects/polltut/yt_tut/yt_tut/views.py", line 87, in done
    return render_to_response('done.html', {'form_data':form_data})
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: done.html
2013-11-27 01:53:31,669 [ERROR] django.request: Internal Server Error: /contact/
Traceback (most recent call last):
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 227, in dispatch
    response = super(WizardView, self).dispatch(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 290, in post
    return self.render_done(form, **kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/contrib/formtools/wizard/views.py", line 332, in render_done
    done_response = self.done(final_form_list, **kwargs)
  File "/Users/mt/Documents/Programming/Python/django/projects/polltut/yt_tut/yt_tut/views.py", line 87, in done
    return render_to_response("done.html", {'form_data':form_data})
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/mt/.virtualenvs/polltut/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: done.html
